name: Verify TTT1 Transfer Chunks

on:
  pull_request:
    branches:
      - ttt

permissions:
  contents: read

jobs:
  verify:
    if: ${{ github.head_ref == 'ttt.1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ttt.1
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ttt.1
          persist-credentials: false
      - name: Verify chunk-00
        continue-on-error: true
        run: echo "e971b6720941eeafc3ae66094e2686ce07922dc6a4fdae9b183d9f13e1690ac2  .github/ttt1-patch/chunk-00" | sha256sum -c -
      - name: Verify chunk-01
        continue-on-error: true
        run: echo "631878ab3c019dd3b937a805c40bc74afd96ecad5912dcfaaae67ce837b3ec8b  .github/ttt1-patch/chunk-01" | sha256sum -c -
      - name: Verify chunk-02
        continue-on-error: true
        run: echo "466a5666b4696b3a5c1e0fa1e401f94968396fbea0e908d55f6e9489c8d95efe  .github/ttt1-patch/chunk-02" | sha256sum -c -
      - name: Verify chunk-03
        continue-on-error: true
        run: echo "be11571a5aea3f24189f5f3beac48d6f74c859ee8e19384d94ae7443531ee74e  .github/ttt1-patch/chunk-03" | sha256sum -c -
      - name: Verify chunk-04
        continue-on-error: true
        run: echo "365c9a326ce30e11a839e1f1491f8209b41a0da79b8392a40b90b06773121087  .github/ttt1-patch/chunk-04" | sha256sum -c -
      - name: Verify chunk-05
        continue-on-error: true
        run: echo "cac84ad2088d2369f5e2e8632c2db07381ee70da9043aaaf78f1b25beb776b10  .github/ttt1-patch/chunk-05" | sha256sum -c -
      - name: Verify chunk-06
        continue-on-error: true
        run: echo "840a8ea1e96c2a31598f2e80dbc12034ea1884c0e0664fce162c7d8c37ef3dc9  .github/ttt1-patch/chunk-06" | sha256sum -c -
      - name: Verify chunk-07
        continue-on-error: true
        run: echo "2ddd8778b2ee39b558d476912328e5c1acb10038f1e868751d990576786ce45d  .github/ttt1-patch/chunk-07" | sha256sum -c -
      - name: Verify chunk-08
        continue-on-error: true
        run: echo "feeeaf8c9444458d3dbb077855f1c527c1ae25a2e065b6ace192068b506ae059  .github/ttt1-patch/chunk-08" | sha256sum -c -
      - name: Verify chunk-09
        continue-on-error: true
        run: echo "a2199b9239bbae7ba57eb23057c5eb8a93db323d9571d6e6f88356af42422735  .github/ttt1-patch/chunk-09" | sha256sum -c -
      - name: Verify chunk-10
        continue-on-error: true
        run: echo "a63fc5e626129c09052d50f33dc3b3eda4ec5016b8384def2a1b1fe0838743aa  .github/ttt1-patch/chunk-10" | sha256sum -c -
      - name: Verify chunk-11
        continue-on-error: true
        run: echo "deff8d6fd6432ad6ba0c4cf355581e51eb6b7dfd06bbf45132d0dbf664be3791  .github/ttt1-patch/chunk-11" | sha256sum -c -
      - name: Verify chunk-12
        continue-on-error: true
        run: echo "d75937de6ff350c50059ff73328ea376fb3657ac5842520140db2fbe53a76b50  .github/ttt1-patch/chunk-12" | sha256sum -c -
